#!/usr/bin/env node
/**
 * d1_to_postgres.mjs — idempotent Cloudflare D1/SQLite → PostgreSQL converter.
 *
 * Input : a directory produced by the read-only D1 export probe
 *           <dir>/schema.json          (sqlite_master rows: type, name, tbl_name, sql)
 *           <dir>/rows/<table>.json    ({ rows: [ {...}, ... ] })
 * Output: <out>/schema.sql   (idempotent DDL, PostgreSQL dialect)
 *         <out>/data.sql     (transactional full-replace load with sequence sync)
 *         <out>/manifest.json (sanitized per-table column/row counts)
 *
 * Dialect rules (kept deliberately close to SQLite so behaviour is unchanged):
 *   - TEXT/INTEGER columns stay TEXT/INTEGER in PostgreSQL, so every existing
 *     value — including timestamp strings such as "2026-07-11 02:29:00" and
 *     empty-string sentinels like "" — is preserved byte for byte.
 *   - CURRENT_TIMESTAMP (SQLite = UTC "YYYY-MM-DD HH:MM:SS") is emitted as the
 *     same UTC text form, so text comparisons and ORDER BY keep working.
 *   - INTEGER PRIMARY KEY AUTOINCREMENT becomes an identity column, and the
 *     sequence is re-synced after every load.
 *
 * No secrets, no network: this script only reads the exported JSON artifacts.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";

const SKIP_TABLES = new Set(["_cf_KV"]); // D1 internal table, not application state
const UTC_TIMESTAMP_SQL = "to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')";

export function convertDdl(sql) {
  let out = String(sql).trim();
  out = out.replace(
    /INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi,
    "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  );
  out = out.replace(/DEFAULT\s+CURRENT_TIMESTAMP/gi, `DEFAULT ${UTC_TIMESTAMP_SQL}`);
  // SQLite INTEGER is 64-bit and REAL is a double; widen both so no value is
  // clipped on the way across (e.g. epoch-millisecond window_start values).
  out = out.replace(/\bREAL\b/gi, "double precision");
  out = out.replace(/\bINTEGER\b/gi, "bigint");
  return out;
}

export function sqlLiteral(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`non-finite number: ${value}`);
    return Number.isInteger(value) ? String(value) : String(value);
  }
  if (typeof value === "bigint") return value.toString();
  if (typeof value === "boolean") return value ? "1" : "0";
  const text = typeof value === "string" ? value : JSON.stringify(value);
  // standard_conforming_strings=on: backslashes are literal, so only quotes need doubling.
  return `'${text.replace(/'/g, "''")}'`;
}

function quoteIdent(name) {
  return `"${String(name).replace(/"/g, '""')}"`;
}

export function buildArtifacts({ schema, rowsByTable }) {
  const tables = schema
    .filter((o) => o.type === "table" && o.sql && !SKIP_TABLES.has(o.name))
    .sort((a, b) => a.name.localeCompare(b.name));
  const indexes = schema
    .filter((o) => o.type === "index" && o.sql && !SKIP_TABLES.has(o.tbl_name))
    .sort((a, b) => a.name.localeCompare(b.name));

  const schemaLines = [
    "-- Generated by tools/migration/d1_to_postgres.mjs — PostgreSQL schema for the",
    "-- migrated jobs.wasfai.com relational store. Idempotent (IF NOT EXISTS).",
    "BEGIN;",
  ];
  for (const t of tables) schemaLines.push(`${convertDdl(t.sql)};`);
  for (const i of indexes) schemaLines.push(`${convertDdl(i.sql)};`);
  schemaLines.push("COMMIT;");

  const dataLines = [
    "-- Generated by tools/migration/d1_to_postgres.mjs — transactional full-replace load.",
    "BEGIN;",
    "SET LOCAL TIME ZONE 'UTC';",
  ];
  const manifest = { tables: {}, totals: { tables: tables.length, rows: 0 } };
  const identityTables = [];

  for (const t of tables) {
    const rows = rowsByTable[t.name] || [];
    const ddl = convertDdl(t.sql);
    if (/\bIDENTITY\b/i.test(ddl)) identityTables.push(t.name);
    dataLines.push(`TRUNCATE TABLE ${quoteIdent(t.name)};`);
    const count = rows.length;
    manifest.tables[t.name] = count;
    manifest.totals.rows += count;
    if (!count) continue;
    const columns = [...new Set(rows.flatMap((r) => Object.keys(r)))];
    const colList = columns.map(quoteIdent).join(", ");
    for (const row of rows) {
      const values = columns.map((c) => sqlLiteral(row[c] === undefined ? null : row[c])).join(", ");
      dataLines.push(`INSERT INTO ${quoteIdent(t.name)} (${colList}) VALUES (${values});`);
    }
  }
  for (const name of identityTables) {
    dataLines.push(
      `SELECT setval(pg_get_serial_sequence('${name}', 'id'), ` +
        `GREATEST(COALESCE((SELECT MAX(id) FROM ${quoteIdent(name)}), 1), 1));`,
    );
  }
  dataLines.push("COMMIT;");

  return {
    schemaSql: schemaLines.join("\n") + "\n",
    dataSql: dataLines.join("\n") + "\n",
    manifest,
  };
}

function main() {
  const [dir, outDir] = process.argv.slice(2);
  if (!dir || !outDir) {
    console.error("usage: d1_to_postgres.mjs <export-dir> <out-dir>");
    process.exit(2);
  }
  const schema = JSON.parse(readFileSync(join(dir, "schema.json"), "utf8")).schema;
  const rowsDir = join(dir, "rows");
  const rowsByTable = {};
  for (const file of readdirSync(rowsDir)) {
    if (!file.endsWith(".json")) continue;
    const table = file.replace(/\.json$/, "");
    if (SKIP_TABLES.has(table)) continue;
    const parsed = JSON.parse(readFileSync(join(rowsDir, file), "utf8"));
    if (parsed.error) throw new Error(`export for ${table} failed: ${parsed.error}`);
    rowsByTable[table] = parsed.rows || [];
  }
  const { schemaSql, dataSql, manifest } = buildArtifacts({ schema, rowsByTable });
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "schema.sql"), schemaSql);
  writeFileSync(join(outDir, "data.sql"), dataSql);
  writeFileSync(join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  console.log(
    `converted ${manifest.totals.tables} tables / ${manifest.totals.rows} rows -> ${outDir}`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) main();
