/**
 * sql.mjs — SQLite/D1 → PostgreSQL SQL translation.
 *
 * The application was written against Cloudflare D1 (SQLite). Rather than
 * rewriting every query, the migration keeps the SQLite-shaped SQL and adapts
 * it at the boundary. This module is the single source of truth for that
 * adaptation, and it is unit-tested (see test/sql.test.mjs).
 *
 * Translations (applied only outside string literals / quoted identifiers):
 *   1. `?` and `?N` placeholders            -> `$1` … `$n`
 *   2. `INTEGER PRIMARY KEY AUTOINCREMENT`  -> identity column
 *   3. `INTEGER` / `REAL` column types      -> `bigint` / `double precision`
 *      (SQLite INTEGER is 64-bit; PostgreSQL `integer` is 32-bit)
 *   4. `CURRENT_TIMESTAMP`                  -> the identical UTC text form
 *      (SQLite stores "YYYY-MM-DD HH:MM:SS" in UTC, and the columns are TEXT)
 *   5. `INSERT OR IGNORE INTO`              -> `INSERT INTO … ON CONFLICT DO NOTHING`
 *
 * Timestamp columns deliberately stay TEXT so every existing value — including
 * empty-string sentinels — round-trips byte for byte.
 */

export const UTC_TIMESTAMP_SQL = "to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')";

/** Split SQL into code and literal segments so rewrites never touch literals. */
export function segmentSql(sql) {
  const segments = [];
  let buffer = "";
  let state = "code";
  let i = 0;
  const push = (type) => {
    if (buffer) segments.push({ type: state === "code" ? "code" : "literal", text: buffer });
    buffer = "";
  };
  while (i < sql.length) {
    const ch = sql[i];
    const next = sql[i + 1];
    if (state === "code") {
      if (ch === "'") { push(); state = "single"; buffer += ch; i += 1; continue; }
      if (ch === '"') { push(); state = "double"; buffer += ch; i += 1; continue; }
      if (ch === "-" && next === "-") { push(); state = "line-comment"; buffer += ch; i += 1; continue; }
      if (ch === "/" && next === "*") { push(); state = "block-comment"; buffer += ch; i += 1; continue; }
      buffer += ch; i += 1; continue;
    }
    if (state === "single") {
      buffer += ch;
      if (ch === "'" && next === "'") { buffer += next; i += 2; continue; }
      if (ch === "'") { push(); state = "code"; }
      i += 1; continue;
    }
    if (state === "double") {
      buffer += ch;
      if (ch === '"' && next === '"') { buffer += next; i += 2; continue; }
      if (ch === '"') { push(); state = "code"; }
      i += 1; continue;
    }
    if (state === "line-comment") {
      buffer += ch; i += 1;
      if (ch === "\n") { push(); state = "code"; }
      continue;
    }
    if (state === "block-comment") {
      buffer += ch; i += 1;
      if (ch === "*" && next === "/") { buffer += next; i += 2; push(); state = "code"; }
      continue;
    }
  }
  push();
  return segments;
}

function rewriteCode(code) {
  let out = code;
  out = out.replace(
    /INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi,
    "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  );
  out = out.replace(/\bREAL\b/gi, "double precision");
  out = out.replace(/\bINTEGER\b/gi, "bigint");
  out = out.replace(/\bCURRENT_TIMESTAMP\b/gi, UTC_TIMESTAMP_SQL);
  return out;
}

function rewritePlaceholders(code) {
  return code.replace(/\?(\d+)?/g, (_m, digits) => (digits ? `$${Number(digits)}` : "?"));
}

export function translateSql(sql) {
  const segments = segmentSql(String(sql));
  const hasIndexed = segments.some((seg) => seg.type === "code" && /\?\d+/.test(seg.text));
  let sequential = 0;
  if (hasIndexed) {
    // Numbering is global across the whole statement, so an explicit `?N`
    // anywhere fixes the starting point for any bare `?` that follows.
    for (const seg of segments) {
      if (seg.type !== "code") continue;
      for (const m of seg.text.matchAll(/\?(\d+)/g)) sequential = Math.max(sequential, Number(m[1]));
    }
  }
  let ignoreInsert = false;
  const translated = segments
    .map((seg) => {
      if (seg.type === "literal") return seg.text;
      if (/INSERT\s+OR\s+REPLACE\s+INTO/i.test(seg.text)) {
        throw new Error("INSERT OR REPLACE is not supported by the PostgreSQL adapter");
      }
      let code = rewriteCode(seg.text);
      code = code.replace(/INSERT\s+OR\s+IGNORE\s+INTO/gi, () => {
        ignoreInsert = true;
        return "INSERT INTO";
      });
      return rewritePlaceholders(code).replace(/\?(\d+)?/g, (_m, digits) => {
        // rewritePlaceholders already replaced every `?N`; only bare `?` remain.
        sequential += 1;
        return `$${sequential}`;
      });
    })
    .join("");
  let out = translated;
  if (ignoreInsert) {
    const trimmed = out.replace(/\s*;\s*$/, "");
    out = `${trimmed} ON CONFLICT DO NOTHING`;
    if (/;\s*$/.test(String(sql))) out += ";";
  }
  return out;
}

/** Highest `$n` present in an already-translated statement (0 when none). */
export function maxPlaceholderIndex(sql) {
  let max = 0;
  for (const seg of segmentSql(String(sql))) {
    if (seg.type !== "code") continue;
    for (const m of seg.text.matchAll(/\$(\d+)/g)) max = Math.max(max, Number(m[1]));
  }
  return max;
}

/** True when the payload is exactly one statement (a trailing ';' is allowed). */
export function isSingleStatement(sql) {
  const stripped = segmentSql(String(sql))
    .filter((s) => s.type === "code")
    .map((s) => s.text)
    .join("");
  const parts = stripped.split(";").map((p) => p.trim()).filter(Boolean);
  return parts.length <= 1;
}

export function countPlaceholders(sql) {
  let n = 0;
  let max = 0;
  for (const seg of segmentSql(String(sql))) {
    if (seg.type !== "code") continue;
    for (const m of seg.text.matchAll(/\?(\d+)?/g)) {
      if (m[1]) max = Math.max(max, Number(m[1]));
      else n += 1;
    }
  }
  return Math.max(max, n);
}

/**
 * Defence in depth: the application only ever needs DML plus the idempotent
 * `CREATE TABLE IF NOT EXISTS` / `CREATE INDEX IF NOT EXISTS` statements its
 * ensure-schema helpers run. Everything destructive or administrative is
 * refused at the gateway even though the bearer token is already required.
 */
const ALLOWED_VERB = /^\s*(select|with|insert|update|delete)\b/i;
const ALLOWED_CREATE =
  /^\s*create\s+table\s+if\s+not\s+exists\b/i;
const ALLOWED_INDEX = /^\s*create\s+(unique\s+)?index\s+if\s+not\s+exists\b/i;

export function assertAllowedStatement(sql) {
  const text = String(sql).replace(/^\s*(--[^\n]*\n|\/\*[\s\S]*?\*\/\s*)*/, "").trim();
  if (ALLOWED_VERB.test(text) || ALLOWED_CREATE.test(text) || ALLOWED_INDEX.test(text)) return text;
  const verb = (text.split(/\s+/)[0] || "").toUpperCase();
  throw Object.assign(
    new Error(`statement verb not permitted by the database gateway: ${verb || "(empty)"}`),
    { statusCode: 400, code: "STATEMENT_NOT_ALLOWED" },
  );
}
