/**
 * sql.mjs — SQLite/D1 → PostgreSQL SQL translation.
 *
 * The application was written against Cloudflare D1 (SQLite). Rather than
 * rewriting every query, the migration keeps the SQLite-shaped SQL and adapts
 * it at the boundary. This module is the single source of truth for that
 * adaptation, and it is unit-tested (see test/sql.test.mjs).
 *
 * Translations (applied only outside string literals / quoted identifiers):
 *   1. `?` and `?N` placeholders            -> `$1` … `$n`
 *   2. `INTEGER PRIMARY KEY AUTOINCREMENT`  -> identity column
 *   3. `INTEGER` / `REAL` column types      -> `bigint` / `double precision`
 *      (SQLite INTEGER is 64-bit; PostgreSQL `integer` is 32-bit)
 *   4. `CURRENT_TIMESTAMP`                  -> the identical UTC text form
 *      (SQLite stores "YYYY-MM-DD HH:MM:SS" in UTC, and the columns are TEXT)
 *   5. `INSERT OR IGNORE INTO`              -> `INSERT INTO … ON CONFLICT DO NOTHING`
 *
 * Timestamp columns deliberately stay TEXT so every existing value — including
 * empty-string sentinels — round-trips byte for byte.
 */

export const UTC_TIMESTAMP_SQL = "to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')";

/** Split SQL into code and literal segments so rewrites never touch literals. */
export function segmentSql(sql) {
  const segments = [];
  let buffer = "";
  let state = "code";
  let i = 0;
  const push = (type) => {
    if (buffer) segments.push({ type: state === "code" ? "code" : "literal", text: buffer });
    buffer = "";
  };
  while (i < sql.length) {
    const ch = sql[i];
    const next = sql[i + 1];
    if (state === "code") {
      if (ch === "'") { push(); state = "single"; buffer += ch; i += 1; continue; }
      if (ch === '"') { push(); state = "double"; buffer += ch; i += 1; continue; }
      if (ch === "-" && next === "-") { push(); state = "line-comment"; buffer += ch; i += 1; continue; }
      if (ch === "/" && next === "*") { push(); state = "block-comment"; buffer += ch; i += 1; continue; }
      buffer += ch; i += 1; continue;
    }
    if (state === "single") {
      buffer += ch;
      if (ch === "'" && next === "'") { buffer += next; i += 2; continue; }
      if (ch === "'") { push(); state = "code"; }
      i += 1; continue;
    }
    if (state === "double") {
      buffer += ch;
      if (ch === '"' && next === '"') { buffer += next; i += 2; continue; }
      if (ch === '"') { push(); state = "code"; }
      i += 1; continue;
    }
    if (state === "line-comment") {
      buffer += ch; i += 1;
      if (ch === "\n") { push(); state = "code"; }
      continue;
    }
    if (state === "block-comment") {
      buffer += ch; i += 1;
      if (ch === "*" && next === "/") { buffer += next; i += 2; push(); state = "code"; }
      continue;
    }
  }
  push();
  return segments;
}

function rewriteCode(code) {
  let out = code;
  out = out.replace(
    /INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi,
    "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  );
  out = out.replace(/\bREAL\b/gi, "double precision");
  out = out.replace(/\bINTEGER\b/gi, "bigint");
  out = out.replace(/\bCURRENT_TIMESTAMP\b/gi, UTC_TIMESTAMP_SQL);
  return out;
}

function rewritePlaceholders(code) {
  const hasIndexed = /\?\d+/.test(code);
  let sequential = 0;
  let maxIndex = 0;
  if (hasIndexed) {
    for (const m of code.matchAll(/\?(\d+)/g)) maxIndex = Math.max(maxIndex, Number(m[1]));
    sequential = maxIndex;
  }
  return code.replace(/\?(\d+)?/g, (_m, digits) => {
    if (digits) return `$${Number(digits)}`;
    sequential += 1;
    return `$${sequential}`;
  });
}

export function translateSql(sql) {
  const segments = segmentSql(String(sql));
  let ignoreInsert = false;
  let translated = segments
    .map((seg) => {
      if (seg.type === "literal") return seg.text;
      if (/INSERT\s+OR\s+REPLACE\s+INTO/i.test(seg.text)) {
        throw new Error("INSERT OR REPLACE is not supported by the PostgreSQL adapter");
      }
      let code = rewriteCode(seg.text);
      code = code.replace(/INSERT\s+OR\s+IGNORE\s+INTO/gi, () => {
        ignoreInsert = true;
        return "INSERT INTO";
      });
      return rewritePlaceholders(code);
    })
    .join("");
  if (ignoreInsert) {
    const trimmed = translated.replace(/\s*;\s*$/, "");
    translated = `${trimmed} ON CONFLICT DO NOTHING`;
    if (/;\s*$/.test(String(sql))) translated += ";";
  }
  return translated;
}

/** True when the payload is exactly one statement (a trailing ';' is allowed). */
export function isSingleStatement(sql) {
  const stripped = segmentSql(String(sql))
    .filter((s) => s.type === "code")
    .map((s) => s.text)
    .join("");
  const parts = stripped.split(";").map((p) => p.trim()).filter(Boolean);
  return parts.length <= 1;
}

export function countPlaceholders(sql) {
  let n = 0;
  let max = 0;
  for (const seg of segmentSql(String(sql))) {
    if (seg.type !== "code") continue;
    for (const m of seg.text.matchAll(/\?(\d+)?/g)) {
      if (m[1]) max = Math.max(max, Number(m[1]));
      else n += 1;
    }
  }
  return Math.max(max, n);
}
